name: test

on:
  - workflow_dispatch
  - push

jobs:
  test:
    runs-on: [self-hosted, ondemand, linux, small]
    env:
      GO111MODULE: on
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Set up Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Run Tests
        run: go test -v ./plugin/... ./internal/...
